### ISSUE TITLE
SDID Event Study Shifted Upwards

### ISSUE THREAD

**Issue by grigoryaleksin** [Daniel-Pailanir/sdid#85] opened 2024-09-26 07:38 UTC
Dear Daniel,

I have used sdid_event to look at a case with staggered adoption. My panel is balanced and sdid works well, but
it feels as if something all the estimated  coefficients are shifted upwards by some constant. Maybe, I have not specified 
some particular option correctly, but intuitively it feels as if something goes wrong. To illustrate the problem, consider the following event study graph from using synthetic control or SDID:

![SC_ES_graph_eror](https://github.com/user-attachments/assets/cf997384-81eb-4694-b0f2-911512730179)
![lm_sdid_event_asb_2yr](https://github.com/user-attachments/assets/d4ffe470-cb9f-426f-99d8-b7ffeb0b3a5b)

In either case, pre-trends are violated but only in level terms which is quite unusual. Any suggestions, if I have made any mistakes code-wise? For example, in the SC I ran:

sdid_event ma_asb numeric_id month_number large_project_one if two_year_count ==0, vce(placebo) brep(50) placebo(12) effects(24) method(sc)

Any help would be much appreciated.

Kind regards,
Grigory

**Comment by damiancclarke** [comment] 2024-09-26 07:57
Hi @grigoryaleksin 

Is there any chance you can provide us with graphical output of the sdid command for this?  If you have a working version of data even better, but with the output of sdid we can probably get more of an idea of what's potentially happening.  

Kind regards,
Damian

**Comment by grigoryaleksin** [comment] 2024-09-26 08:15
Dear Damian,

I can make a subset asap of my data that replicates the issue (otherwise it will take about 12hrs to run with the full sample). Since I have many adoption dates, the graphical output from SDID would yield me a large gallery of graphs. I can run it and get all of them, or was there something else you were thinking of?

Kind regards,
Grigory

**Comment by grigoryaleksin** [comment] 2024-09-26 11:37
Dear Damian,

Attached are a data extract and DO file that can replicate the problem. Without inference, as is done in the DO, it runs in under 20mins.

[SC Error.zip](https://github.com/user-attachments/files/17147614/SC.Error.zip)

Kind regards,
Grigory

**Comment by grigoryaleksin** [comment] 2024-10-04 16:55
![graph_event_study](https://github.com/user-attachments/assets/41eab0c6-e18b-4e84-925c-907a9b8e74d9)
![sdid_event](https://github.com/user-attachments/assets/1c7dca62-4fed-4c9e-9c8e-7c9a946f7d51)

To given another replication of the error, I have picked a cohort in the middle of the sample. The two graphs are given above. In the first case, the large pre-trend violations that sdid_event give should probably not be there.

**Comment by damiancclarke** [comment] 2024-10-09 18:55
Hi @grigoryaleksin,

I'm sorry it's taken a little bit of time to address this.  It turns out that this was caused by a bug which occurred when `placebo()` and `effects()` were used with less than the maximum number.  In cases such as these, the placebo effects returned were actually grabbing true post treatment effects.  This has been corrected in a bug fix incorporated into sdid_event today by @DiegoCiccia.  I have tried with your data, and example, and this all appears to be corrected.  If you re-install the version of `sdid_event` on the github page, this should all be corrected now.  We will update this in the SSC in the near future. 

Apologies for the delay in responding to this, and any inconveniences this has caused.  

I will close this issue for now, but please feel free to write here in case of any questions, concerns, etc.  Thanks very much for reporting this, and for such a clearly documented example!

Best wishes,
Damian

**Closed by damiancclarke** 2024-10-09 18:55 UTC
